# Lab 1: Tensor Manipulation

First Author: Seungjae Ryan Lee (seungjaeryanlee at gmail dot com)
Second Author: Ki Hyun Kim (nlp.with.deep.learning at gmail dot com)

<div class="alert alert-warning">
    NOTE: This corresponds to <a href="https://www.youtube.com/watch?v=ZYX0FaqUeN4&t=23s&list=PLlMkM4tgfjnLSOjrEJN31gZATbcj_MpUm&index=25">Lab 8 of Deep Learning Zero to All Season 1 for TensorFlow</a>.
</div>

## Imports

Run `pip install -r requirements.txt` in terminal to install all required Python packages.

In [1]:
import numpy as np
import torch

## NumPy Review

We hope that you are familiar with `numpy` and basic linear algebra.

### 1D Array with NumPy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


## PyTorch is like NumPy (but better)

### 1D Array with PyTorch

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [11]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [12]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch

### [mul](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) vs. [matmul](https://pytorch.org/docs/stable/generated/torch.matmul.html#torch.matmul)

In [23]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
print("tensor.matmul (a,b) is matrix mulitplication")
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f"m1: {m1}")
print(f"m2: {m2}")
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1

print(f"m1.matmul(m2):\n {m1.matmul(m2)}") # 2 x 1

print("="*20)
print("a*b or tensor.mul(b) is element-wise mulitplication")
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f"m1: {m1}")
print(f"m2: {m2}")
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(f"m1*m2:\n {m1 * m2}") # 2 x 2
print(f"m1.mul(m2):\n {m1.mul(m2)}")


-------------
Mul vs Matmul
-------------
tensor.matmul (a,b) is matrix mulitplication
m1: tensor([[1., 2.],
        [3., 4.]])
m2: tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
m1.matmul(m2):
 tensor([[ 5.],
        [11.]])
a*b or tensor.mul(b) is element-wise mulitplication
m1: tensor([[1., 2.],
        [3., 4.]])
m2: tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
m1*m2:
 tensor([[1., 2.],
        [6., 8.]])
m1.mul(m2):
 tensor([[1., 2.],
        [6., 8.]])


### [Broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html?highlight=broadcasting)

<div class="alert alert-warning">
    Carelessly using broadcasting can lead to code hard to debug.
</div>

In [24]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [25]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [26]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])  # [[1,2]] ==> [ [1,2], p1,2] }
m2 = torch.FloatTensor([[3], [4]])# [[3],[4]] ==> [ [3,3], [4,4]]
print(m1 + m2)   

tensor([[4., 5.],
        [5., 6.]])


### [mean](https://pytorch.org/docs/stable/generated/torch.mean.html#torch.mean)

In [27]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [28]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


You can also use `t.mean` for higher rank tensors to get mean of all elements, or mean by particular dimension.

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(t.mean())       # element-wise maen : (1+2+3+4)/2
print(t.mean(dim=0))  # row-wise mean  : [(1+3)/2, (2+4)/2]
print(t.mean(dim=1))  # colum-wis mean : [(1+2)/2, (3+4)/2]
print(t.mean(dim=-1)) # colum-wis mean: [(1+2)/2, (3+4)/2]

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### [sum](https://pytorch.org/docs/stable/tensors.html?highlight=sum#torch.Tensor.sum)

In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.sum())       # element-wise sum : 1+2+3+4
print(t.sum(dim=0))  # row-wise sum : [ 1+3, 2+4]
print(t.sum(dim=1))  # colum-wis sum: [(1+2), (3+4)]
print(t.sum(dim=-1)) # colum-wis sum: [(1+2), (3+4)]

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### [max](https://pytorch.org/docs/stable/generated/torch.max.html) and [argmax](https://pytorch.org/docs/stable/tensors.html?highlight=argmax#torch.Tensor.argmax)

In [42]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The [torch.max()](https://pytorch.org/docs/stable/generated/torch.max.html) operator returns one value if it is called without an argument.

In [43]:
print(t.max()) # Returns one value: max

tensor(4.)


The [torch.Tensor.max()](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.max) operator returns 2 values when called with dimension specified. The first value is the maximum value, and the second value is the [torch.Tensor.argmax()](https://pytorch.org/docs/stable/tensors.html?highlight=argmax#torch.Tensor.argmax): the index of the element with maximum value.

In [44]:
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])    # first element of returned list is max value
print('Argmax: ', t.max(dim=0)[1]) # seocond element of returned list is index of cell that contains max value

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [45]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### [View](https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view)

<div class="alert alert-warning">
    This is a function hard to master, but is very useful!
</div>

[torch.Tensor.view](https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view)  
view(*shape) → Tensor
* Returns a new tensor with the same data as the self tensor but of a different shape.

The returned tensor shares the same data and must have the same number of elements, but may have a different size. For a tensor to be viewed, the new view size must be compatible with its original size and stride, i.e., each new view dimension must either be a subspace of an original dimension, or only span across original dimensions $d, d+1, \dots, d+k$ that satisfy the following contiguity-like condition that $\forall i = d, \dots, d+k-1$ ,
$$
\text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
$$

When it is unclear whether a [view()](https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view) can be performed, it is advisable to use [reshape()](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape), which returns a view if the shapes are compatible, and copies (equivalent to calling [contiguous()](https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.contiguous) otherwise.

In [46]:
t = np.array([
               [[0, 1, 2],
               [3, 4, 5]
              ],
              [
               [6, 7, 8],
               [9, 10, 11]
              ]
              ])
ft = torch.FloatTensor(t)  # convert np.array to torch.FloatTensor
print(ft.shape)

torch.Size([2, 2, 3])


In [47]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [48]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### [Squeeze](https://pytorch.org/docs/stable/generated/torch.squeeze.html#torch.squeeze)

squeeze(dim=None) → Tensor

Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape: $(A \times 1 \times B \times C \times 1 \times D)$ then the out tensor will be of shape: $(A \times B \times C \times D)$.

When ```dim``` is given, a squeeze operation is done only in the given dimension. If input is of shape: $(A \times 1 \times B)$, squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape $(A \times B)$.

In [49]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [41]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### [unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html#torch.unsqueeze)  

torch.unsqueeze(input, dim) → Tensor

Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

A ```dim``` value within the range ```[-input.dim() - 1, input.dim() + 1)``` can be used. Negative ```dim``` will correspond to unsqueeze() applied at ```dim = dim + input.dim() + 1```.

In [32]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [33]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [34]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [35]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [36]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### [scatter](https://pytorch.org/docs/stable/tensors.html?highlight=scatter#torch.Tensor.scatter_) (for one-hot encoding)

<div class="alert alert-warning">
    Scatter is a very flexible function. We only discuss how to use it to get a one-hot encoding of indices.
</div>

scatter_(dim, index, src, reduce=None) → Tensor

Writes all values from the tensor ```src``` into ```self``` at the indices specified in the ```index``` tensor. For each value in ```src```, its output index is specified by its index in ```src``` for ```dimension != dim``` and by the corresponding value in ```index``` for ```dimension = dim```.

For a 3-D tensor, self is updated as:
````
self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0
self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1
self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2
````
This is the reverse operation of the manner described in [gather()](https://pytorch.org/docs/stable/generated/torch.gather.html#torch.gather).

In [50]:
# index list for change the values to one in each row
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [51]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1) # dim=1, index= lt ??
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [39]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [40]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [41]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [42]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### [Concatenation](https://pytorch.org/docs/stable/generated/torch.cat.html?highlight=torch%20tensor%20cat)

torch.cat(tensors, dim=0, *, out=None) → Tensor

Concatenates the given sequence of ```seq``` tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

[torch.cat()](https://pytorch.org/docs/stable/generated/torch.cat.html?highlight=torch%20tensor%20cat#torch.cat) can be seen as an inverse operation for [torch.split()](https://pytorch.org/docs/stable/generated/torch.split.html#torch.split) and [torch.chunk()](https://pytorch.org/docs/stable/generated/torch.chunk.html#torch.chunk).

In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [54]:
print(torch.cat([x, y], dim=0))   # vertical stacking
print(torch.cat([x, y], dim=1))   # horizontal stacking

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### [Stacking](https://pytorch.org/docs/stable/generated/torch.stack.html?highlight=torch%20stack#torch.stack)

torch.stack(tensors, dim=0, *, out=None) → Tensor

Concatenates a sequence of tensors along a new dimension.

All tensors need to be of the same size.

In [55]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [56]:
print(torch.stack([x, y, z]))     # vertical stacking
print(torch.stack([x, y, z], dim=1))  # horizontal stacking

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [47]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros Like

[torch.ones_like()](https://pytorch.org/docs/stable/generated/torch.ones_like.html?highlight=ones_like#torch.ones_like)

Returns a tensor filled with the scalar value 1, with the same size as ```input```. ```torch.ones_like(input)``` is equivalent to ```torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)```.

[torch.zeors_like()](https://pytorch.org/docs/stable/generated/torch.zeros_like.html?highlight=zeros_like)

Returns a tensor filled with the scalar value 0, with the same size as ```input```. ```torch.zeros_like(input)``` is equivalent to ```torch.zeros(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)```.

In [48]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [49]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

[torch.Tensor.mul_()](https://pytorch.org/docs/stable/tensors.html?highlight=torch%20mul_#torch.Tensor.mul) is In-place version of mul().

Note that operators by underline are in-place version. i.e, change the data in the Tesor instead of make copy.

In [50]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [57]:
print(x.mul(2.))   
print(x)
print(x.mul_(2.))  # in-place version mul
print(x)

tensor([2., 8.])
tensor([1., 4.])
tensor([2., 8.])
tensor([2., 8.])


## Miscellaneous

### Zip

파이썬 함수인 zip(*iterable)은 동일한 개수로 이루어진 자료형을 묶어 주는 역할을 하는 함수이다.

````
>>> list(zip([1, 2, 3], [4, 5, 6]))
[(1, 4), (2, 5), (3, 6)]
>>> list(zip([1, 2, 3], [4, 5, 6], [7, 8, 9]))
[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
>>> list(zip("abc", "def"))
[('a', 'd'), ('b', 'e'), ('c', 'f')]
````

In [52]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [53]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
